apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
      - name: todo-app
        image: anatoly5602/todo-app:latest
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_ENV
          value: development
        - name: FLASK_DEBUG
          value: '1'
      - name: mongo
        image: mongo:latest
        ports:
        - containerPort: 27017
